import type { Metadata } from 'next'
import { Montserrat, DM_Sans } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Querencia Pre-order',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const dm_sans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dm_sans',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${dm_sans.variable}`}>
      <body className="relative flex flex-col items-center">
        <header className="fixed flex w-full max-w-screen-xl justify-between">
          <div>Logo</div>
          <nav>
            <ul className="flex" role="menu">
              <li>Product Details</li>
              <li>FAQ</li>
              <li>Contact</li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
